version: "3.8"

services:
  text2srt_tts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text2srt_tts_app
    ports:
      - "8501:8501"
    volumes:
      # Mount task directory for persistent output files
      - ./task:/app/task
      # Mount config file (optional)
      - ./config.toml:/app/config.toml:ro
    environment:
      # Streamlit configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Optional Azure TTS configuration (set these in your .env file)
      - AZURE_KEY=${AZURE_KEY:-}
      - AZURE_REGION=${AZURE_REGION:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - text2srt_network

networks:
  text2srt_network:
    driver: bridge

volumes:
  task_data:
    driver: local
